name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 #git clone of container 
    - name: make           #steps to be executed
      run: make test
    - name: run test
      run: ./test    #-s flag to show expanded version of test run: all assertions sent and evaluations.
      #can add tag in TEST_CASE("name of test", "[tag]"){} can filter by tag:  ./test [tag]
